config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :professors

  devise_scope :student do  
    get '/students/sign_out' => 'devise/sessions#destroy'   
  end

  devise_scope :professor do  
    get '/professors/sign_out' => 'devise/sessions#destroy'   
  end


  resources :university_subjects
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/professor.rb
class Professor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :university_subjects
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/university_subject.rb
class UniversitySubject < ApplicationRecord

    belongs_to :professor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :student_code)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @userLogged = (current_student || current_professor)
  end
end

app/controllers/university_subjects_controller.rb
class UniversitySubjectsController < ApplicationController
  before_action :set_university_subject, only: %i[ show edit update destroy ]
  before_action :authenticate_professor!, except: [:index, :show]
  before_action :correct_professor, only: [:edit, :update, :destroy]

  def index
    begin
      if student_signed_in?
        @university_subjects = UniversitySubject.where(
          student_code: current_student.student_code.to_s
        )
      if professor_signed_in?
        @university_subjects = UniversitySubject.where(
          professor_id: current_professor.id 
        )
      end
      else 
        @university_subjects = UniversitySubject.where(
          professor_id: 1
        )
      end
    rescue Exception => e
      puts e.message
    end
  
  end

  def show
  end

  def new
    begin
      @university_subject = current_professor.university_subjects.build
    rescue Exception => e
      puts e.message
    end
  end

  def create
    @university_subject = current_professor.university_subjects.build(university_subject_params)

    respond_to do |format|
      if @university_subject.save
        ApplicationJob.perform_later()
        format.html { redirect_to university_subject_url(@university_subject), notice: "Nota criada com sucesso!" }
        format.json { render :show, status: :created, location: @university_subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @university_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @university_subject.update(university_subject_params)
        format.html { redirect_to university_subject_url(@university_subject), notice: "A nota foi atualizada com sucesso!" }
        format.json { render :show, status: :ok, location: @university_subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @university_subject.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @university_subject.destroy

    respond_to do |format|
      format.html { redirect_to university_subjects_url, notice: "Nota deletada com sucesso!" }
      format.json { head :no_content }
    end
  end

  def correct_professor
    @universitySubject = current_professor.university_subjects.find_by(id: params[:id])
    redirect_to university_subjecs, notice: "Não autorizado a editar esta nota" if @universitySubject.nil?
  end

  private
    def set_university_subject
      @university_subject = UniversitySubject.find(params[:id])
    end

    def university_subject_params
      params.require(:university_subject).permit(:student_code, :coordinator, :bimester, :grade, :comment, :professor_id, :student_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_name(user)
        if user
            "Olá #{user.email.split('@', -1)[0]} !"
        else
            "Inicie sua sessão ou efetue o cadastro!"
        end
    end
end

app/helpers/devise_request_spec_helper.rb
module DeviseRequestSpecHelper
    include Warden::Test::Helpers

    def sign_in(resource_or_scope, resource = nil)
      resource ||= resource_or_scope
      scope = Devise::Mapping.find_scope!(resource_or_scope)
      login_as(resource, scope: scope)
    end
  
    def sign_out(resource_or_scope)
      scope = Devise::Mapping.find_scope!(resource_or_scope)
      logout(scope)
    end
end

app/helpers/form_helper.rb
module FormHelper
    def errors_for(form, field)
        content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
    end

    def form_group_for(form, field, opts={}, &block)
        label = opts.fetch(:label) { true }
        has_errors = form.object.errors[field].present?

        content_tag :div, class: "form-group #{'has-error' if has_errors}" do
            concat form.label(field, class: 'control-label') if label
            concat capture(&block)
            concat errors_for(form, field)
        end
    end
end

app/helpers/university_subjects_helper.rb
module UniversitySubjectsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark" >
  <div class="container-fluid">
    <%= link_to 'Faculdade ABC', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
         <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        
        <% if professor_signed_in? %>
          
          <li class="nav-item">
            <%= link_to "Ver Notas", university_subjects_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Lançar nova nota", new_university_subject_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Editar Perfil", edit_professor_registration_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sair", destroy_professor_session_path, method: :delete, class: "nav-link"%>
          </li>

        <% end %>
 
        <% if student_signed_in? %>
         
          <li class="nav-item">
            <%= link_to "Ver Notas", university_subjects_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Editar Perfil", edit_student_registration_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sair", destroy_student_session_path, method: :delete, class: "nav-link"%>
          </li>
        <% end %>

        <% if !student_signed_in? && !professor_signed_in? %>
          <li class="nav-item">
            <%= link_to "Cadastrar", new_student_registration_path, class: "nav-link"%>
          </li>
          
          <li class="nav-item">
            <%= link_to "Conectar", new_student_session_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
          <%= link_to "Acessar como Professor", new_professor_session_path, class: "nav-link"%>
          </li>
        <% end %>

      
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home</h1>
<p>Sistema para cadastro de notas de alunos</p>
<p> <%= format_name(@userLogged) %> </p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
      
    <title>Faculdade ABC</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
   <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/university_subjects/_form.html.erb
<%= form_with(model: university_subject) do |form| %>
  <% if university_subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(university_subject.errors.count, "error") %> prohibited this university_subject from being saved:</h2>

      <ul>
        <% university_subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group w-25">
    <%= form.text_field :student_code, required: true, required: true, label: true, class: "form-control", placeholder:"RA do aluno" %>
  </div>

  <div class="field form-group w-25">
    <%= form.text_field :coordinator, class: "form-control", required: true, label: true, placeholder:"Responsável por aplicar a prova" %>
  </div>

  <div class="field form-group w-25">
    <%= form.text_field :bimester, class: "form-control", required: true, label: true, placeholder: "Bimestre" %>
  </div>

  <div class="field form-group w-25">
    <%= form.text_field :grade, class: "form-control", required: true, label: true, placeholder: "Nota" %>
  </div>

  <div class="field form-group w-25">
    <%= form.text_area :comment, class: "form-control", placeholder: "Comentário" %>
  </div>

  <div class="field form-group w-25">
    <%= form.number_field :professor_id, id: :university_subject_professor_id, class: "form-control", value: current_professor.id, type: :hidden  %>
  </div>

  <div>
    <%= form.submit 'Finalizar', class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/university_subjects/_university_subject.html.erb
<div id="<%= dom_id university_subject %>">
  <td>
    <%= university_subject.student_code %>
  </td>

  <td>
    <%= university_subject.coordinator %>
  </td>

  <td>
    <%= university_subject.bimester %>
  </td>

  <td>
    <%= university_subject.grade %>
  </td>

  <td>
    <%= university_subject.comment %>
  </td>

  <td>
    <%= link_to 'Exibir', university_subject, class: 'btn btn-primary' %>
  </td>

  <% if university_subject.professor == current_professor %>
    <td>
      <%= link_to 'Editar', edit_university_subject_path(university_subject), class: 'btn btn-secondary' %>
    </td>
    <td>
      <%= link_to 'Deletar', university_subject, method: :delete, data: { confirm: "Tem certeza que deseja deletar esta nota?" }, class: 'btn btn-danger' %>
    </td>
  <% else %>
    <td></td>
    <td></td>
  <% end %>
</div>

app/views/university_subjects/edit.html.erb
<h1>Notas</h1>

<%= render "form", university_subject: @university_subject %>

<br>

<div>
  <%= link_to "Mostrar Detalhes da Nota", @university_subject %> |
  <%= link_to "Voltar para Notas", university_subjects_path %>
</div>

app/views/university_subjects/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>RA do Aluno</th>
      <th>Responsável</th>
      <th>Bimestre</th>
      <th>Nota</th>
      <th>Comentário </th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="university_subjects">
    <% @university_subjects.all.map do |university_subject| %>
      <tr></tr>
        <%= render university_subject %>
      <% end %>
  </tbody>
</table>

app/views/university_subjects/new.html.erb
<h1>Nova Nota</h1>

<%= render "form", university_subject: @university_subject %>

app/views/university_subjects/show.html.erb
<div class="jumbotron">
  <h3 class="font-weight-bold">RA Número:</h3>
  <h4><%= @university_subject.student_code %></h4>
  <h3 class="font-weight-bold">Responsável:</h3>
  <h4><%= @university_subject.coordinator %></h4>
  <h3 class="font-weight-bold">Bimestre:</h3>
  <h4><%= @university_subject.bimester %></h4>
  <h3 class="font-weight-bold">Nota: </h3>
  <h4><%= @university_subject.grade %></h4>
  <h3 class="font-weight-bold">Comentários:</h3>
  <div>
    <%= @university_subject.comment %> 
  </div>
  <hr class="my-4">
  <p class="lead">
    <%= link_to "Voltar", university_subjects_path, class:"btn btn-secondary" %>  
    <% if professor_signed_in? %>
      | <%= link_to "Editar", edit_university_subject_path(@university_subject), class:"btn btn-secondary" %> |
      <%= button_to "Deletar", @university_subject, method: :delete, class:"btn btn-dark" %>
    <% end %>
  </p>
</div>